-- =============================================================================
-- Migration: 006_ai_reports.sql
-- Adds the ai_reports table for storing AI Mentor Report results.
--
-- One report per student per exam. Re-submitting overwrites via upsert on
-- the (student_id, exam_id) unique constraint.
--
-- Run in: Supabase Dashboard → SQL Editor
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.ai_reports (
  id                   UUID        NOT NULL DEFAULT uuid_generate_v4(),
  student_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  exam_id              UUID        NOT NULL REFERENCES public.exams(id) ON DELETE CASCADE,
  submission_id        UUID        NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  report_text          TEXT        NOT NULL DEFAULT '',
  readiness_score      INTEGER     NOT NULL DEFAULT 0,
  predicted_low        INTEGER     NOT NULL DEFAULT 0,
  predicted_high       INTEGER     NOT NULL DEFAULT 0,
  learning_profile     VARCHAR(64) NOT NULL DEFAULT '',
  strengths_text       TEXT,
  weaknesses_text      TEXT,
  recommendations_text TEXT,
  generated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT ai_reports_pkey               PRIMARY KEY (id),
  CONSTRAINT ai_reports_student_exam_unique UNIQUE (student_id, exam_id),
  CONSTRAINT ai_reports_readiness_range     CHECK (readiness_score BETWEEN 0 AND 100),
  CONSTRAINT ai_reports_predicted_range     CHECK (predicted_high >= predicted_low)
);

COMMENT ON TABLE public.ai_reports IS
  'AI Mentor Reports generated by Claude after each exam submission. '
  'One report per student per exam — upserted on re-submission.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_reports_student_id
  ON public.ai_reports (student_id);

CREATE INDEX IF NOT EXISTS idx_ai_reports_generated_at
  ON public.ai_reports (generated_at DESC);

-- =============================================================================
-- Row Level Security
-- =============================================================================

ALTER TABLE public.ai_reports ENABLE ROW LEVEL SECURITY;

-- Students read only their own reports
CREATE POLICY "ai_reports: student reads own"
  ON public.ai_reports
  FOR SELECT
  TO authenticated
  USING (auth.uid() = student_id);

-- Admins have full access (uses the non-recursive helper from migration 004)
CREATE POLICY "ai_reports: admin full access"
  ON public.ai_reports
  FOR ALL
  TO authenticated
  USING (public.requesting_user_is_admin());

-- =============================================================================
-- Done.
-- Verify: SELECT * FROM public.ai_reports LIMIT 5;
-- =============================================================================
